### PR TITLE
InlineSpinner: fix forward ref

### PR DESCRIPTION
**Pull request by florianduros**
Closes https://github.com/element-hq/compound-web/issues/187

### CODE REVIEW

**Review by t3chguy — COMMENTED** [review]
What if the caller does need a ref on the spinner?

**Comment by florianduros** [comment]
> What if the caller does need a ref on the spinner?

When I try to use a forwared ref on it, I have the following error: `Property ref does not exist on type: IntrinsicAttributes & SVGAttributes<SVGElement>`

**Comment by t3chguy** [comment]
Sounds like the svg loader needs fixing to support refs

**Review by dbkr — APPROVED** [review]

**Comment by florianduros** [comment]
@t3chguy created an issue to track it https://github.com/element-hq/compound-web/issues/192

**Pull request merged**
